list_movies/urls.py
from django.urls import path
from list_movies.views import show_all_movie_review, show_all_movie_details, like_view


app_name = 'list'

urlpatterns = [
    path('', show_all_movie_review, name='all'),
    path('details/<int:pk>', show_all_movie_details, name='details'),
    path('like/<int:pk>', like_view, name='like')
]

movie_review/urls.py
from django.contrib import admin
from django.urls import path, include
from movie_review.views import homepage_view, troll_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage_view),
    path('list/', include('list_movies.urls')),
    path('users/', include('users.urls')),
    path('troll/', troll_view)
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import login_user, register_user,logout_users,show_profile

app_name='users'

urlpatterns=[
    path('login/', login_user,name='login'),
    path('logout/', logout_users, name='logout'),
    path('register/', register_user, name='register'),
    path('profile/', show_profile, name='profile')
]

list_movies/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.db.models import Max


class Product(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False)
    type = models.CharField(max_length=200, null=False, blank=False)
    description = models.TextField()
    profile_image = models.ImageField(null=False, blank=False, upload_to="images/")
    second_image = models.ImageField(null=False, blank=False, upload_to="images/")
    third_image = models.ImageField(null=False, blank=False, upload_to="images/")
    rating = models.DecimalField(max_digits=3, decimal_places=1, default=0)
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    avg = models.DecimalField(max_digits=2, decimal_places=1, default=0)
    nr_com = models.DecimalField(max_digits=4, decimal_places=1, default=0)
    likes = models.ManyToManyField(User, related_name='blog_post')
    total_like = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def total_likes(self):
        return self.likes.count()

    def most_likes(self):
        return self.likes.aggregate(most_like=Max('like'))


class Order(models.Model):
    avg = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)


RATE_CHOICES =[
    (1, '1 - Trash'),
    (2, '2 - Bad'),
    (3, '3 - OK'),
    (4, '4 - Good'),
    (5, '5 - Perfect'),
]


class Comment(models.Model):
    post = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length=160)
    timestamp = models.DateTimeField(blank=True, default=datetime.now)
    stars = models.PositiveSmallIntegerField(choices=RATE_CHOICES)

    def __str__(self):
        return '{}'.format(self.post.name)

list_movies/forms.py
from django import forms
from .models import Comment, RATE_CHOICES, Product, Order


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'materialize-textarea'}), required=True)
    stars = forms.ChoiceField(choices=RATE_CHOICES, widget=forms.Select(), required=True)

    class Meta:
        model = Comment
        fields = ('content', 'stars')


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('avg', 'nr_com')


class OrderForm(forms.Form):
    class Meta:
        model = Order
        fields = '__all__'

list_movies/views.py
from django.shortcuts import render, HttpResponse, Http404, get_object_or_404, redirect, reverse
from django.http import HttpResponseRedirect
from .models import Product, Comment
from users.models import Profile
from .forms import *
from django.db.models import Avg, Max
from datetime import datetime
from django.contrib import messages
from django.core.paginator import Paginator
from django.urls import reverse
from .filters import OrderFilter
from .forms import OrderForm


def show_all_movie_review(request):

    products = Product.objects.all()
    paginator = Paginator(products, 5)

    page_obj = paginator.get_page(request.GET.get('page', 1))

    my_filter = OrderFilter()

    context = {
        'page_obj': page_obj,
        'my_filter': my_filter,
    }
    return render(request, 'list/list.html', context)


def show_all_movie_details(request, pk):
    post = Product.objects.get(id=pk)
    comments = Comment.objects.filter(post=post)

    nr_com = comments.count()
    avg = average_review(pk)
    Product.objects.filter(id=pk).update(nr_com=nr_com, avg=avg)
    each_product = Product.objects.get(id=pk)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('content')
            stars = request.POST.get('stars')

            user_id = request.user.id
            coins = request.user.profile.coins
            coins = coins + 10

            last_comm = content
            timestamp = datetime.now()

            Profile.objects.filter(user_id=user_id).update(coins=coins, last_comm=last_comm, timestamp=timestamp)

            comment = Comment.objects.create(post=post, user=request.user, stars=stars, content=content)
            comment.save()
            messages.success(request, 'Thanks for your submit! You receive +10 coins!')

            return redirect(reverse('list:details', args=(pk,)))

    else:
        comment_form = CommentForm()

    stuff = get_object_or_404(Product, id=pk)
    total_likes = stuff.total_likes()
    liked = False

    if stuff.likes.filter(id=request.user.id).exists():
        liked = True

    context = {
        'each_product': each_product,
        'comments': comments,
        'comment_form': comment_form,
        'total_likes': total_likes,
        'liked': liked,
    }

    return render(request, 'list/details.html', context)


def average_review(pk):
    reviews = Comment.objects.filter(post_id=pk).aggregate(average=Avg('stars'))

    avg = 0
    if reviews['average'] is not None:
        avg = float(reviews['average'])
        avg = round(avg, 1)
    return avg


def like_view(request, pk):
    post = get_object_or_404(Product, id=request.POST.get('each_product_pk'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
        total_like = Product(pk).total_likes()
        Product.objects.filter(id=pk).update(total_like=total_like)
    else:
        post.likes.add(request.user)
        liked = True
        total_like = Product(pk).total_likes()
        Product.objects.filter(id=pk).update(total_like=total_like)

    return HttpResponseRedirect(reverse('list:details', args=(pk,)))

list_movies/templates/list/details.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <title>{{list.name}}</title>
    {% endblock %}

{% block head %}
     <div class='container'>
                <div class='row justify-content-center'>

                    {% if messages %}
                        <ul class="messages">
                        {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                        </ul>
                    {% endif %}

                    <div class="row">
                        <div class="col">
                            <img src="{{each_product.profile_image.url}}" class="img-fluid rounded" width= "300" height="100" >
                        </div>
                        <div class="col">

                                <h5 class="card-title">{{each_product.name}}</h5>
                                <h6 class="card-title">Our Rating: {{each_product.rating}} </h6>

                                    <h7 class="card-title">Comments AVG : {{each_product.avg}}</h7>



                                <p class="card-text"> {{each_product.description}} {{each_product.nr_com}} </p>

                        </div>
                    </div>
                </div>

                <img src="{{each_product.profile_image.url}}" class="img-fluid rounded-start" width= "100" height="75" >
                <img src="{{each_product.second_image.url}}" class="img-fluid rounded-start" width= "100"  height="75">
                <img src="{{each_product.third_image.url}}" class="img-fluid rounded-end" width= "100"  height="75">

                <br><br>
                {% if request.user.is_authenticated %}
                    <form action ="{% url 'list:like' each_product.pk%}" method="POST">
                    {% csrf_token %}
                    {% if liked %}
                        <button type="submit", name="each_product_pk", value="{{ each_product.pk }}", class="btn btn-danger btn-sm" > Unlike </button>
                    {% else %}
                        <button type="submit", name="each_product_pk", value="{{ each_product.pk }}", class="btn btn-primary btn-sm" > Like </button>
                    {%endif%}

                    - {{ total_likes }} Likes
                    </form>
                {%else%}
                    (Login to like) {{ total_likes }} Likes

                {%endif%}
                <br><br>

                <hr>
                    <div class="main-comment-selection">
                        {{ comments.count }} Comments
                        {% for comment in comments %}
                            <figure>
                            <blockquote class="blockquote">
                                <p class="mb-2"> {{ comment.content }}   {{ comment.avg }} </p>
                            </blockquote>
                            <footer class="blockquote-footer">
                            Commented by <cite title="Source Title"> {{ comment.user }} </cite>  Stars <cite title="Source Title"> {{ comment.stars }} </footer>
                            </figure>
                            {%endfor%}
                    </div>

                    {% if request.user.is_authenticated %}

                    <form method="post" action="" role="form" class="col s6">
                        {% csrf_token %}
                        <div class="input-field col s6">
                        Stars: {{ comment_form.stars }}
                        </div>

                        <div class="input-field col s6">
                        Comment:
                        <br>
                        <div class="materialize-textarea" cols="60" rows="3" >
                        {{ comment_form.content }}
                        </div>

                        <input type="submit" value="Add comment" class="btn btn-outline-success">
                        </div>
                    </form>
                        {%endif%}


                <a href="/list/" class='btn btn-primary'>Back</a>
     </div>

     {% endblock %}

list_movies/templates/list/list.html
{% extends 'base.html' %}


    {% block body %}

        <title> Movie Page</title>

        <h1> Movie page</h1>

              Salutare!


       {% endblock %}


    {% block head %}
     <ul>

        {% if page_obj.paginator.num_pages > 1 %}
           <div class="row">
                <div class="col-12">
                    {% if page_obj.has_previous %}
                        <a href="{% url 'list:all' %}?page={{page_obj.previous_page_number}}">Previous page </a>
                    {%else%}
                        <div>The first page.</div>
                    {%endif%}
                    <div>Current page {{page_obj.number}} </div>
                    {% if page_obj.has_next %}
                        <a href="{% url 'list:all' %}?page={{page_obj.next_page_number}}">Next page </a>
                    {%else%}
                        <div>The last page.</div>
                    {%endif%}

                </div>
            </div>

            <form method="get">
                {{my_filter.form}}
            <button class="btn btn-primary" type="submit">Search</button>
            </form>

            {% for product in page_obj %}
                <div class='container'>
                <div class='row justify-content-center'>
                <div class="card mb-3" style="max-width: 890px;">
                    <div class="card text-white bg-secondary " style="max-width: 100rem;">
                    <div class="row">
                        <div class="col">

                            <img src="{{ product.profile_image.url }}" class="img-fluid rounded" width= "150"  height="75" alt="...">
                        </div>

                        <div class="col-sm-9">
                            <br>
                            <div class="row">
                                <div class="col-sm-5">

                                    <h5 class="card-title">{{product.name}}  </h5>
                                </div>
                                <div class="col-sm-5">

                                       <h6 class="card-title"> Comments Rating: {{product.avg}} </h6>




                                    <h6 > Our Rating: {{product.rating}}</h6>
                                </div>
                            </div>
                            <p class="card-text"> {{product.description}}</p>
                            <p class="card-text"> {{product.total_like}} Likes</p>
                            <a href="{% url 'list:details' product.pk %}" class='btn btn-primary mt-2'>Details</a>

                        </div>
                    </div>
                </div>
                </div>
                </div>
                {%endfor%}

        {%else%}
          <p> No movies...</p>

        {%endif%}

       </ul>

     {% endblock %}