list_movies/urls.py
from django.urls import path
from list_movies.views import show_all_movie_review, show_all_movie_details, like_view


app_name = 'list'

urlpatterns = [
    path('', show_all_movie_review, name='all'),
    path('details/<int:pk>', show_all_movie_details, name='details'),
    path('like/<int:pk>', like_view, name='like')
]

movie_review/urls.py
from django.contrib import admin
from django.urls import path, include
from movie_review.views import homepage_view, troll_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage_view),
    path('list/', include('list_movies.urls')),
    path('users/', include('users.urls')),
    path('troll/', troll_view)
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import login_user, register_user,logout_users,show_profile

app_name='users'

urlpatterns=[
    path('login/', login_user,name='login'),
    path('logout/', logout_users, name='logout'),
    path('register/', register_user, name='register'),
    path('profile/', show_profile, name='profile')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <div class="row">
        <div class="col-sm-1">
        </div>

        <div class="col-sm-10">

            <body>

                {% include 'menu.html' %}
                {% block body %}
                    {% endblock %}
                {% block content %}
                    {% endblock %}

            </body>

            <head>

            {% block head %}
                {% endblock %}

            </head>
        </div>

        <div class="col-sm-1">
        </div>

    </div>

</html>

templates/homepage.html
{% extends 'base.html' %}
{% load static %}
    {% block head %}
        <title> Home Page</title>
        {% endblock %}


        {% block body %}
        <img src="{% static 'images/logo2.png' %}" width="100" />
            <div class="container">
                <div class="centered">
                {% if request.user.is_authenticated %}
                    <h1 style="text-align:center">WELCOME {{ request.user.username }}</h1>
                {%else%}
                    <h1 style="text-align:center">WELCOME guest</h1>
                {%endif%}
            </div>
        </div>

        <br><br>

        <div class="row">
            <p1>This is the Homepage!</p1>
        </div>
        <div class="row">
            <p1>This is one of the best site in the world! Here you can find different types on reviews from users that have anything to say.</p1>
        </div>
        <div class="row">
            <p2>I hope that you can tell us your opinion and our community will be glad to read it!</p2>
        </div>







        {% endblock %}

templates/menu.html
        <nav>
        {% load static %}
            <br>
            <div class="row">
                <div class="col-sm-1">
                    <a href="/" >Homepage</a>
                </div>

                <div class="col-sm-1">
                    <a href="{% url 'list:all'%}" >List</a>
                </div>

               <div class="col-sm-1">
                  {% if request.user.is_superuser %}
                    <a href="/admin/" >Admin</a>
                  {%else%}
                    <a href="/troll/" >Admin</a>
                    {% endif %}
               </div>
               <div class="col-sm-6">
               </div>

               <div class="col-sm-3">
                  {% if not request.user.is_authenticated %}
                    <a href="{% url 'users:login'%}" >Login</a>
                    <a href="{% url 'users:register'%}" >Register</a>

                  {% else %}
                    <img src="{% static 'images/coins.png' %}" width="20" />
                    Coins:{{ request.user.profile.coins}}
                    <img src="{{ request.user.profile.image }}" width="30" height="30" />
                    <a href="{% url 'users:profile'%}" >Profile</a>
                    <a href="{% url 'users:logout'%}" >Logout</a>


                    {% endif %}
               </div>

            </div>

        </nav>

templates/troll.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>troll</title>
</head>
<body>
    <br>
    <h1>TROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLL</h1>
    <h1>TROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLL</h1>
    <h1>TROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLL</h1>
    <h1>TROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLL</h1>
    <h1>TROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLL</h1>
    <h1>TROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLL</h1>
    <h1>TROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLL</h1>
    <h1>TROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLL</h1>
    <h1>TROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLL</h1>
    <h1>TROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLL</h1>
    <h1>TROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLL</h1>
    <h1>TROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLL</h1>
    <h1>TROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLL</h1>
    <h1>TROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLL</h1>
    <h1>TROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLLTROLL</h1>

</body>
</html>